### ISSUE TITLE
Escopo do projeto

### ISSUE THREAD

**Issue by inteligenciamilgrau** [inteligenciamilgrau/assistentemilgrau#1]
### Assistente Mil Grau
#fazorobô
1. Conversar
- [x] Fazer computador falar
- [x] Fazer computador ouvir
- [x] Fazer integração com arduino
- [x] Fazer chatbot para conversar com o Assistente Mil Grau
2. Enxergar
- [x] Ligar WebCam
- [x] Detectar Rosto
- [x] Seguir Rosto
- [x] Conectar Arduino
- [x] Integrar no Assistente
3. Pegar coisas
- [x] Controlar braço robótico com fio
- [x] Controlar braço robótico sem fio
- [x] Detectar objeto com WebCam
- [x] Seguir objeto
- [x] Pegar objeto
4. Andar
- [x] Fazer driver do motor funcionar
- [x] Integrar com controle WiFi
- [x] Integrar com Python
- [ ] Integrar Câmera
- [ ] Fazer Detecção de Pessoas
- [ ] Seguir Pessoas
- [ ] Integrar com Aplicativo para Celular

**Comment by FranciscoStanley** [comment]
Olá, eu tive um problema em fazer o computador me ouvir.
PS C:\Users\Franc\Documents\projeto-jarvis> & C:/Users/Franc/AppData/Local/Programs/Python/Python37/python.exe c:/Users/Franc/Documents/projeto-jarvis/ouvirVoz.py
Traceback (most recent call last):
  File "C:\Users\Franc\AppData\Local\Programs\Python\Python37\lib\site-packages\speech_recognition\__init__.py", line 108, in get_pyaudio
    import pyaudio
ModuleNotFoundError: No module named 'pyaudio'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:/Users/Franc/Documents/projeto-jarvis/ouvirVoz.py", line 5, in <module>
    mic = sr.Microphone()
  File "C:\Users\Franc\AppData\Local\Programs\Python\Python37\lib\site-packages\speech_recognition\__init__.py", line 79, in __init__    
    self.pyaudio_module = self.get_pyaudio()
  File "C:\Users\Franc\AppData\Local\Programs\Python\Python37\lib\site-packages\speech_recognition\__init__.py", line 110, in get_pyaudio
    raise AttributeError("Could not find PyAudio; check installation")
AttributeError: Could not find PyAudio; check installation
PS C:\Users\Franc\Documents\projeto-jarvis>

**Comment by FranciscoStanley** [comment]
> Olá, eu terei um problema em fazer o computador me ouvir.
> PS C: \ Usuários \ Franc \ Documentos \ projeto-jarvis> & C: /Users/Franc/AppData/Local/Programs/Python/Python37/python.exe c: / Usuários / Franc / Documentos / projeto-jarvis / ouvirVoz. py
> Traceback (última chamada mais recente):
> Arquivo "C: \ Users \ Franc \ AppData \ Local \ Programs \ Python \ Python37 \ lib \ site-packages \ speech_recognition_ _init_ _.py", linha 108, em get_pyaudio
> import pyaudio
> ModuleNotFoundError: Nenhum módulo chamado 'pyaudio'
> 
> Durante o tratamento da exceção acima, outra exceção ocorreu:
> 
> Traceback (última chamada mais recente):
> Arquivo "c: /Users/Franc/Documents/projeto-jarvis/ouvirVoz.py", linha 5, em
> mic = sr.Microphone ()
> Arquivo "C: \ Users \ Franc \ AppData \ Local \ Programs \ Python \ Python37 \ lib \ site-packages \ speech_recognition_ _init_ _.py ", linha 79, em **init**
> self.pyaudio_module = self.get_pyaudio ()
> Arquivo" C: \ Users \ Franc \ AppData \ Local \ Programs \ Python \ Python37 \ lib \ site-packages \ speech_recognition_ _init_ _.py ", linha 110, em get_pyaudio
> raise AttributeError (" Não foi possível encontrar PyAudio; verificar instalação ")
> AttributeError: Não foi possível encontrar PyAudio; verificar instalação
> PS C: \ Usuários \ Franc \ Documentos \ projeto-jarvis>

eu consegui resolver o meu problema eu só comentei esse trecho de código(#4rr.adjust_for_ambiente_noise(fonte). ) e funcionou.

**Comment by raa-russo** [comment]
Muito top, parabéns!
